use_frameworks!

platform :ios, '13.0'

target 'EasyObserve_Example' do
  pod 'EasyObserve', :path => '../'

  target 'EasyObserve_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
